### ISSUE TITLE
来自刚毕业的校友的感谢…

### ISSUE THREAD

**Issue by AXinsLab** [sbtobb/dlnujxpg#2]
非常感谢你，要是毕业前能想到过来逛一逛，就能节省点时间了
本来想学了编程以后，给学弟学妹们开发一个，这下好了，没动力了，你赔我学习的动力…

**Comment by yaukwan** [comment]
哈哈哈哈，同届
你可以fork过去完善一下，或者重写一个网页版本也行

**Comment by AXinsLab** [comment]
好的，等我学到炉火纯青了，一定在此基础上重新搞一个
